apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
